### ISSUE TITLE
the phar is not working on HHVM

### ISSUE THREAD

**Issue by stof** [scrutinizer-ci/ocular#10]
The phar is reported as corrupted in HHVM: https://travis-ci.org/Behat/MinkBrowserKitDriver/jobs/24218053#L122

**Comment by xabbuh** [comment]
Can anyone else confirm that this is working (again) with the `hhvm` and `hhvm-nightly` builds?

**Comment by schmittjoh** [comment]
If not, you can always use the packagist package "scrutinizer/ocular" instead if you would like to send data from an HHVM build.

**Comment by xabbuh** [comment]
Thanks for the hint, @schmittjoh. I don't need it at the moment (I just didn't send the reports in HHVM builds as suggested by @stof in https://github.com/scrutinizer-ci/ocular/issues/10#issuecomment-43234672). Though this might be interesting for others as well.

**Comment by williamdes** [comment]
@stof maybe close this issue, HHVM is not something anymore
