### ISSUE TITLE
Upgrade Guzzle dependency

### ISSUE THREAD

**Issue by pkruithof** [scrutinizer-ci/ocular#15]
The current version is very old, and will be EOL soon. I can submit a PR if you're interested?

**Comment by schmittjoh** [comment]
I would recommend to use the phar file instead of adding ocular as a dependency to your project. In that case, it should not matter how old the linked version is, no?

**Comment by pkruithof** [comment]
I like the dev-dependency as it can be cached by Travis. Maybe I can tweak it to cache the phar as well.

But besides that, Guzzle should still be upgraded, don't you think? :wink:

**Comment by matejsvajger** [comment]
guzzle/guzzle is now abandoned and moved to guzzlehttp/guzzle. Would be great to get rid of the warning message from composer.

**Comment by marcovtwout** [comment]
Fixed with https://github.com/scrutinizer-ci/ocular/pull/34

**Comment by marcovtwout** [comment]
@schmittjoh This one can now be closed :)

**Comment by schmittjoh** [comment]
Thanks :+1:
