### ISSUE TITLE
Not compatible with Symfony 5

### ISSUE THREAD

**Issue by colinodell** [scrutinizer-ci/ocular#47]
PR #44 added support for installing Symfony 5 components, but this project is actually **NOT** compatible with `symfony/process` 5.x.  The ability to accept a string as the first parameter of the `Process` constructor was [deprecated in 4.2](https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/Process/Process.php#L147) and [removed in 5.0](https://github.com/symfony/symfony/blob/5.0/src/Symfony/Component/Process/Process.php#L140).  See the [CHANGELOG](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Process/CHANGELOG.md) for more information.

As a result, requiring version 1.7.0 of this project on newer versions of PHP leads to fatal errors like https://github.com/thephpleague/commonmark/issues/410:

![](https://user-images.githubusercontent.com/2829600/73730432-a75a4480-472e-11ea-898a-b1d2fac6b805.png)

**Comment by peterfox** [comment]
Also got this problem currently. Had to use `master-dev` in two packages I work on until this is resolved as Laravel now requires Symfony 5 components.

**Comment by marcovtwout-tremani** [comment]
Reverted to 1.6.0 until this is fixed.

**Comment by secondtruth** [comment]
I've created pull request #49 to fix this.

**Comment by schmittjoh** [comment]
Closing this as fixed a while ago.
