### ISSUE TITLE
Not compatible with PHP 8

### ISSUE THREAD

**Issue by annuh** [scrutinizer-ci/ocular#51]
I found that the latest `ocular.phar` is not compatible with PHP 8.

Steps to reproduce:
```
docker run -it php:8-cli /bin/bash -c "apt-get update && apt-get install -y wget && wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --repository test --revision test --parent test ."
```

This is error message that is returned:
```
root@7df1e08850a8:/# php ocular.phar code-coverage:upload --repository test --revision test --parent test .
Notifying that no code coverage data is available for repository "test" and revision "test"...

  [Guzzle\Common\Exception\InvalidArgumentException]
  Invalid handle provided
```

Resource handlers are changed in PHP 8: https://php.watch/versions/8.0/resource-CurlHandle.
A newer `guzzle` fixed the issue.

**Comment by mindplay-dk** [comment]
Was this change ever published? I'm [still getting this error](https://travis-ci.org/github/mindplay-dk/middleman/jobs/760690577).

**Comment by annuh** [comment]
> Was this change ever published? I'm [still getting this error](https://travis-ci.org/github/mindplay-dk/middleman/jobs/760690577).

I'm not sure if [ocular.phar](https://scrutinizer-ci.com/ocular.phar) is updated, but I've added the Ocular package as a devDependency to our `composer.json`:

```json
"require-dev": {
        "scrutinizer/ocular": "dev-master",
}
```

and use it like `vendor/bin/ocular`.

**Comment by villfa** [comment]
This action can also be used as a workaround: https://github.com/sudo-bot/action-scrutinizer
