### ISSUE TITLE
`ocular.phar` doens't work with PHP 8?

### ISSUE THREAD

**Issue by mindplay-dk** [scrutinizer-ci/ocular#62]
Uploading code coverage with your tool no longer works.

Here's the [output from a failed build](https://app.travis-ci.com/github/mindplay-dk/sql/jobs/589630229):

```
$ php ocular.phar code-coverage:upload --format=php-clover test/build/clover.xml
Uploading code coverage for repository "g/mindplay-dk/sql" and revision "ab4325ea8e0aaa84c39c7c4fa990ab6dd0220bc5"... 
                                                      
  [Guzzle\Common\Exception\InvalidArgumentException]  
  Invalid handle provided                             
```

I recently switched to PHP 8, so maybe your tool needs an upgrade to support that?

**Comment by schmittjoh** [comment]
Yes, the ocular.phar is a very old version. I would recommend to use composer to install ocular either globally in your environment or as a dev dependency, then composer will get the right version for your PHP version.

With the ocular.phar distribution we are bound to break things for some people as we do not know in what environment you will run this unfortunately.

**Comment by mindplay-dk** [comment]
> Yes, the ocular.phar is a very old version [...] With the ocular.phar distribution we are bound to break things for some people as we do not know in what environment you will run this unfortunately.

Since you know this doesn't actually work, it might be time to update your [official documentation](https://scrutinizer-ci.com/docs/tools/external-code-coverage/) then? Your PHP example still shows exactly the thing I'm doing, which doesn't work anymore.

> I would recommend to use composer to install ocular either globally in your environment or as a dev dependency, then composer will get the right version for your PHP version.

You probably should show both of those examples in your documentation.

Some people might want this as a dev dependency - I personally would prefer installing this globally, since the dependency (probably?) isn't useful for local development and primarily intended for CI.
